server {
    listen 8080;
    host 127.0.0.1;
    root ../www/site1;
    methods GET;
}

server {
    listen 8081;
    host 192.168.1.5;
    root ../www/site2;
    index home.html;
    methods GET DELETE;
}
