pid logs/nginx.pid;

events {
	worker_connections 1024;
}

http {
	access_log logs/access.log;
	error_log logs/error.log;

	server {
		listen 8080;
		root .;
		index html/index.html;


		location /autoindex {
			limit_except GET {
				deny all;
			}
			autoindex on;
		}

		location /noautoindex {
			limit_except GET {
				deny all;
			}
		}

		location /upload {
			limit_except POST {
				deny all;
			}
			# IRL: needs to be handled with a backend
			return 201;
		}

		location /delete {
			# usually handled with a proper backend return 201;
			dav_methods DELETE;
			create_full_put_path on;
			dav_access user:rw group:rw all:r;
			# return 200 "$request_filename\n";
			# # usually handled with a proper backend # return 204;
		}

		location /cgi-bin/ {
			# must do python3 -m http.server --cgi 9001 from nginx_test
			proxy_pass http://127.0.0.1:9001/cgi-bin/;
		}
	}
}

