server {
	listen 9080;
	host 127.0.0.1;
	root nginx_test;
	index html/index.html;

	location /upload {
		methods POST;
		upload_enable on;
		upload_store /upload;
	}

	location /autoindex {
		methods GET;
		autoindex on;
	}

	location /noautoindex {
		methods GET;
	}

	location /delete {
		methods DELETE;
	}

	cgi .py /usr/bin/python3;

	location /cgi-bin/ {
		methods POST GET;
	}

}
