
server {
	listen 8081;
	host 127.0.0.1;
	root www;
	index index.html;
	server_name facoleur.ch;
	methods GET;
}

server {
	listen 8080;
	host 127.0.0.1;
	root www;
	server_name example.com;
	# index about.html;
	methods GET POST;
	client_max_body_size 5;

	location /www {
		autoindex on;
		client_max_body_size 2;
		upload_enable on;
		upload_store upload;
		methods GET POST;
	}

	location /dir {
		client_max_body_size 10;
		autoindex on;
		root www;
		upload_enable on;
		upload_store /upload;
		methods GET POST;
	}

	cgi .py /usr/bin/python3;

	location /cgi-bin {
		client_max_body_size 50;
		methods GET POST;
	}

	location /del {
		methods DELETE;
	}

	location /delroot {
		root www/files;
		methods DELETE;
	}
}
