server {
	listen 8080;
	host 127.0.0.1;
	root ./www;
	index index.html index.htm;
	methods GET;

	location /www/ {
		root ./www;
		methods GET;
	}

	location /legacy {
		return 301 /Fame.mp3;
	}
}

# server {
# 	listen 8081;
# 	host 127.0.0.1;
# 	root /var/www/foo-server;
# 	index foo;
# 	methods GET;
# }
