
server {
	listen 8081;
	host 127.0.0.1;
	root www;
	index index.html;
	methods GET;
}

server {
	listen 8080;
	host 127.0.0.1;
	root www;
	server_name example.com;
	index index.html index.htm;
	methods GET POST;
	client_max_body_size 20;

	location /www {
		client_max_body_size 10;
		root .;
		upload_enable on;
		upload_store /upload;
		methods GET POST;
	}

	location /dir {
		autoindex on;
		root www/dir;
		methods GET POST;
	}

	# location /getonly {
	# 	autoindex on;
	# 	root /www/dir;
	# 	methods GET DELETE;
	# }

	# location /delete {
	# 	root www/delete;
	# 	methods DELETE;
	# }

	# location /upload {
	# 	client_max_body_size 1048576;
	# 	upload_enable on;
	# 	upload_store /upload;
	# 	methods POST;
	# }

	# location /upload/limited {
	# 	client_max_body_size 5;
	# 	upload_enable on;
	# 	upload_store /upload;
	# 	methods POST;
	# }

	# location /legacy {
	# 	return 301 /Fame.mp3;
	# }
}
