server {
    listen 8082;
    host 127.0.0.1;
    root ../www;
    index index.html;
    methods GET POST DELETE;
    autoindex off;
    client_max_body_size 1048576;
    error_page 404 /errors/404.html;

    cgi .py /usr/bin/python3;
    cgi .sh /bin/bash;

    location /upload {
        methods POST;
        upload_enable on;
        upload_store ../uploads;
        client_max_body_size 2097152;
        autoindex off;
    }
}

