server {
host 127.0.0.1;
listen 8080;
listen 8082;

root ../www/site1;
index index.html;
methods GET;
autoindex off;
error_page 404 /errors/404.html;
}

server {
host 192.168.1.50;
listen 9000;

root /var/www/site2;
index home.html;
methods GET DELETE;

location /legacy {
    return 301 /moved.html;
}
}