server {
host 127.0.0.1;
listen 8080;
listen 8081;

root ../www/site;
index index.html index.htm;
methods GET POST;

location /upload {
    methods POST;
    upload_enable on;
    upload_store ../uploads;
    client_max_body_size 2097152;
}
}